waf:
  build: "."
  command: ['gunicorn', '-w6', '-b 0.0.0.0:5000', 'antlion.antlion:app' ]
  ports:
   - "5000:5000"
  links:
   - dummy_service
  volumes:
   - ./config/antlion.ini:/root/antlion.ini
   - .:/opt/antlion

dummy_service:
  build: "./test_service"
  command: ['python', '/opt/dummyservice/antlion_dummy.py']
  ports:
    - "5500:5500"
  volumes:
    - ./test_service/:/opt/dummyservice/
